name: 'Buildroot'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - name: Run
      run: |
          wget https://buildroot.org/downloads/buildroot-2024.02.tar.xz
          tar xf buildroot-2024.02.tar.xz
          cd buildroot-2024.02
          pwd
          make defconfig
          cat <<EOF >> .config
          BR2_TARGET_ROOTFS_OCI=y
          BR2_TARGET_ROOTFS_OCI_ENTRYPOINT="df"
          BR2_TARGET_ROOTFS_OCI_CMD="-h"
          BR2_TARGET_ROOTFS_OCI_ARCHIVE=y
          EOF
          make
      shell: bash
